theme: jekyll-theme-minimal
title: L. Guillermo Woo Mora
description: Hi! Thanks for visiting my webpage
plugins:
  - jekyll-multiple-languages-plugin
show_downloads: false
github:
  is_project_page: true
  languages: ["sp", "en"]
