theme: jekyll-theme-minimal
title: L. Guillermo Woo Mora
description: 
markdown: kramdown
plugins:
  - jekyll-multiple-languages-plugin
  - jemoji
show_downloads: false
github:
  is_project_page: true
  languages: ["sp", "en"]
