theme: jekyll-theme-minimal
title: L. Guillermo Woo Mora
description: 
pages:
  home: Home
  work: Work
plugins:
  - jekyll-multiple-languages-plugin
show_downloads: false
github:
  is_project_page: true
  languages: ["sp", "en"]
